// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oghivfkvvhgeisgdxkrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9naGl2Zmt2dmhnZWlzZ2R4a3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTE0ODEsImV4cCI6MjA3MzU2NzQ4MX0.zrR9fPrN7v3fKR-mXIuftWj5o64d4mKOc-mnF1qPnD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});